### ISSUE TITLE
Missing values in Gateway.Capability

### ISSUE THREAD

**Issue by TrodelHD** [marchof/three4j#30]
General Description:
+ It seams like Threema has updated the possible capabilities and now `Gateway.Capability` is missing some values.

Way to reproduce:
+ When I try to request the capabilities of my ThreemaId with `Gateway#getCapabilities(ThreemaId threemaid)` I receive the following exception:
```
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.mountainminds.three4j.Gateway.Capability.ballot
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.mountainminds.three4j.Gateway$Capability.valueOf(Gateway.java:232)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.mountainminds.three4j.Gateway.getCapabilities(Gateway.java:248)
```
Reason

+ The reason is that the result of the request contains `ballot,call,videocall,image,file,text,video,audio,pfs,group,groupcall` and the enum only contains `text, image, video, audio, file`.

Suggestions

* The missing values should be added to the enum
* Instead of using `Capability::valueOf` some other mapping method should be used that doesn't throw an exception when trying to map to `Gateway.Capability`
Example:
 ```
stream(result.split(","))
            .map(str -> Arrays.stream(Capability.values()).filter(cap -> cap.name().equals(str)).findFirst())
            .filter(Optional::isPresent)
            .map(Optional::get)
            .collect(toSet());
```

**Comment by marchof** [comment]
Thanks for pointing this out. Please see PR #31 and feel free to add review comments.

**Comment by TrodelHD** [comment]
Looks completely fine to me.

Thank You for responding so fast .

**Comment by marchof** [comment]
@TrodelHD I just prepared release 1.4.0. If you have some time here is the staging repo for testing:

https://s01.oss.sonatype.org/content/repositories/commountainminds-1012/

**Comment by TrodelHD** [comment]
For my application the 1.4.0 repo works but I only tested/need:
+ checking the capability of the target
+ fetching the public key of the target
+ sending an encrypted text message to the target

**Comment by marchof** [comment]
Release 1.4.0 should be available. Thanks for your contribution!
